
DROP TABLE IF EXISTS tblusers;
CREATE TABLE tblusers(
    Id INT NOT NULL IDENTITY(1,1)
    ,UserId VARCHAR(255) NOT NULL UNIQUE
    ,Username VARCHAR(40) NOT NULL UNIQUE
    ,Password VARCHAR(255) NOT NULL
    ,Email VARCHAR(255) NOT NULL UNIQUE
    ,RefreshToken VARCHAR(255) NOT NULL DEFAULT "none"
    ,CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
    ,UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
    ,CONSTRAINT PK_User PRIMARY KEY(UserId)
);
